name: Setup Bun project
description: Node, Bun, cache e install

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v7
      with:
        node-version: "24.19.0"
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: "1.3.14"
    - uses: actions/cache@v6
      with:
        path: node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-
    - run: bun install
      shell: bash
    - run: bun run compile:i18n
      shell: bash

